### ISSUE TITLE
[CI] Github Actions out of disk space

### ISSUE THREAD

**Issue by Azzerty23** [zenstackhq/zenstack#1016]
**Description and expected behavior**
Tests generate a lot of files and leads to out of disk space error.

Error: `System.IO.IOException: No space left on device : '/home/runner/actions-runner/_diag/Worker_20240220-144619-utc.log'`
Warning: `You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 66 MB`

Would it be possible to clean generated files after each test suite?

**Additional context**
It happened here: https://github.com/zenstackhq/zenstack/actions/runs/7975313695

**Comment by TGTGamer** [comment]
So the likely solution to this is to split out the tests to reduce how much load is on each of the runners. Instead of testing the entire workspace as one, split it based on the paths. 

You could either do this using: 
```
            - name: Check for changes in packages/schema and packages/api
              id: check-changes
              run: |
                  echo "::set-output name=schema_changed::$(git diff --name-only HEAD^ HEAD | grep 'packages/schema' && echo true || echo false)"
                  echo "::set-output name=api_changed::$(git diff --name-only HEAD^ HEAD | grep 'packages/api' && echo true || echo false)"
              shell: bash

            - name: Test
              # if a file in the packages/schema or packages/api directory changes, run the tests
              if: ${{ steps.check-changes.outputs.schema_changed == 'true' || steps.check-changes.outputs.api_changed == 'true' }}
              run: pnpm run test-ci
```

or you could split the actual file and then use: 
```
env:
    TELEMETRY_TRACKING_TOKEN: ${{ secrets.TELEMETRY_TRACKING_TOKEN }}
    DO_NOT_TRACK: '1'
    PATH: packages/schema

on:
  pull_request:
    branches: ['dev', 'main']
    paths: 
      packages/schema/**
```

Both of these options would allow you to test just the individual modules, reducing the used space. 
I would recommend option 2, it would give you the most freedom and be the easiest to maintain. 

@ymc9 let me know which you prefer and I'll throw a PR together

**Comment by Azzerty23** [comment]
@ymc9 As CI is fixed, do you want me to close this issue, or are you still interested in the split tests proposal by @TGTGamer?

**Comment by ymc9** [comment]
> @ymc9 As CI is fixed, do you want me to close this issue, or are you still interested in the split tests proposal by @TGTGamer?

The test infra uses the [tmp](https://www.npmjs.com/package/tmp) package to create temp folders (npm projects), which are supposed to be cleaned up when the process (jest) exits. It's possible that for larger test suites, one jest instance is responsible for running many cases, so the cleanup is too late.

It seems it doesn't happen anymore. We can keep watching it for a while.

I actually want to see if it's possible to run most of the cases without creating temp npm projects at all. That'll make test runs faster too. Otherwise, need to somehow split the test runs. The most costly tests are those in "tests/integration". They're meant to be run for all changes to cover potential unexpected breaks.

**Comment by ymc9** [comment]
I've split tests into several CI jobs. Closing for now.
