### ISSUE TITLE
CLI errs when running generate without network connection

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#1529]

**Comment by aloisklink** [comment]
Potentially related to https://github.com/zenstackhq/zenstack/issues/1464

Ideally, there should also be some sort of timeout (e.g. 1 second), so that if you're on a slow network connection, running `generate` doesn't take a long time (I've encountered this issue before when running `zenstack generate` while on a train with a spotty internet connection).

I wonder if it's worth just creating a custom version checker function, e.g. something like: https://github.com/promptfoo/promptfoo/blob/fb6cbce74b0d627c7a6811923cb4f4d983e5ff73/src/updates.ts

Both [`get-latest-version`](https://www.npmjs.com/package/get-latest-version) and [`latest-version`](https://www.npmjs.com/package/latest-version) don't have timeouts.

**Comment by ymc9** [comment]
> Potentially related to #1464
> 
> Ideally, there should also be some sort of timeout (e.g. 1 second), so that if you're on a slow network connection, running `generate` doesn't take a long time (I've encountered this issue before when running `zenstack generate` while on a train with a spotty internet connection).
> 
> I wonder if it's worth just creating a custom version checker function, e.g. something like: https://github.com/promptfoo/promptfoo/blob/fb6cbce74b0d627c7a6811923cb4f4d983e5ff73/src/updates.ts
> 
> Both [`get-latest-version`](https://www.npmjs.com/package/get-latest-version) ~and [`latest-version`](https://www.npmjs.com/package/latest-version)~ don't have timeouts. _Edit_: [`latest-version`](https://www.npmjs.com/package/latest-version) seems to have a 10s timeout by default, but it's not possible to change.

Yes, it's a bit unfortunate the packages don't support timeout ... I'm replacing it fetch with timeout. Thanks for providing the reference implementation!
