### ISSUE TITLE
CLI should report error when a non-existent config file is specified

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#343]

**Comment by potion-cellar** [comment]
I was looking at this and it seemed like it *does* -- at least at the `preAction` in `/packages/schema/src/cli/index.ts`.

But in the actual `loadConfig` function of `config.ts` there is no check (just an early return) so a little bit of a code smell here.

In my PR #354 I went ahead and moved the existence check to the `loadConfig` function with the correct `CliError` throw. I also adjusted the logic there a bit and wrote / tweaked some tests to better detect what sort of errors are being thrown in some scenarios.

Hopefully that's useful, couldn't really tell what this issue was really referring to besides ensuring a useful `CliError` is being emitted if the user-specified config file path does not exist.

**Comment by ymc9** [comment]
Fixed in release [alpha.111](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-alpha.111).
