### ISSUE TITLE
Genereated Trpc routes does not return types for relations

### ISSUE THREAD

**Issue by Azzerty23** [zenstackhq/zenstack#409]
**Description and expected behavior**
Generated Trpc routes do not allow for retrieving the types of relationships (`include`).

**Screenshots**
✅ With original Prisma client:
<img width="495" alt="Capture d’écran 2023-05-10 à 11 25 43" src="https://github.com/zenstackhq/zenstack/assets/43639468/cb86d1ca-9904-43f4-8433-db4c3813d6c0">

❌ With **generated trpc routes**:
<img width="521" alt="Capture d’écran 2023-05-10 à 11 26 52" src="https://github.com/zenstackhq/zenstack/assets/43639468/661f2fa5-0f60-4c5e-be80-5c51a7effdd6">

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-alpha.116
-   Prisma version: 4.12.0
-   Database type: Postgresql

**Additional context**
When I overwrite the generated procedure...
<img width="530" alt="Capture d’écran 2023-05-10 à 13 10 24" src="https://github.com/zenstackhq/zenstack/assets/43639468/330205cd-565b-4221-9583-39b9617ad921">
...typing works well
<img width="517" alt="Capture d’écran 2023-05-10 à 13 06 59" src="https://github.com/zenstackhq/zenstack/assets/43639468/2136f68d-6391-443b-afd0-24258567914e">
But I don't have the solution to dynamically attach types to the procedure input.

**Comment by Azzerty23** [comment]
As a workaround, destructuring the input object allows all relations to be present, but as optional.
<img width="560" alt="Capture d’écran 2023-05-10 à 13 52 18" src="https://github.com/zenstackhq/zenstack/assets/43639468/20f6e1cf-b2c4-4ad6-ac63-04e7e420d578">

**Comment by ymc9** [comment]
Hi @Azzerty23 ,

Thanks for bringing this up. Unfortunately, this is a current limitation of tRPC. Due to the way how tRPC infers types, the router's typing is determined statically and cannot automatically adapt to the input's shape as Prisma could. Here's a github issue about this topic: https://github.com/trpc/trpc/issues/3311.

As suggested in the github discussion, it's possible to wrap another layer of hooks around the trpc router to achieve such kind of typing (pretty much what ZenStack is doing with the `@zenstackhq/react` plugin for generating react hooks), but that'll introduce more complexity and also strange to use because it doesn't look like using tRPC anymore ...

The workaround you suggested can also be useful, although not ideal. At least you can get autocompletion to work for the relation fields. Maybe we can make that change to the trpc plugin?

**Comment by Azzerty23** [comment]
I was not aware of this limitation in tRPC. I understand that you do not want to tweak tRPC. I hope that this issue will be solved through an enhancement of TypeScript and tRPC implementation. In the meantime, having an option to opt-in for the workaround would be great for sure!

**Comment by ymc9** [comment]
Cool. Let me think about how to express that "opt-in" 😄.

**Comment by ymc9** [comment]
Hi, @Azzerty23 I'm thinking about this issue again, and I feel maybe we can do something to "fix" trpc's typing, by casting its client hooks appropriately. Are you using trpc over Next.js with `createTRPCNext` now?

**Comment by ymc9** [comment]
I spent some time poking around trpc's typing and couldn't find a way to hack it on the server-side router definition, but I think we can probably fix it on the trpc client side, since we're doing code generation anyway.

The change may look like this:

```ts
import { enhance } from '../routers/generated/next-utils.ts';

const trpc = enhance(createTRPCNext<AppRouter>({
    ...
}));
```

The `enhance` function is generated and only does type-casting, turning hooks like `findMany` etc. into Prisma-style generic typing so that the output's type adapts to the input.

What's unfortunate is the casting is client-specific, so I guess separate code needs to be generated for different client frameworks. Haven't looked deeply into this yet.

Does this make sense to you in general?

**Comment by Azzerty23** [comment]
I see, indeed it seems to be the best approach!

**Comment by ymc9** [comment]
Thanks! I'll continue exploring this route then.

**Comment by ymc9** [comment]
Hi @Azzerty23 , this has been added in the latest "beta.3" release.

https://zenstack.dev/docs/reference/plugins/trpc#client-helpers
