### ISSUE TITLE
[Feature Request] Plugin for JetBrains editors

### ISSUE THREAD

**Issue by giovanni-orciuolo** [zenstackhq/zenstack#519]
I would like to write `zmodel` files in a JetBrains editor (e.g. IDEA/WebStorm). Are there plans to add this in the future?
In case not, is there a language server I can use to build this plugin myself? Similar to what happens with the VS Code extension.

Thank you in advance!

**Comment by jiashengguo** [comment]
Thanks for trying out ZenStack! 

Unfortunately that we don't have a plan to support IntelliJ/JetBrains in the short term yet.

Our VScode extension uses another OSS project [Langium](https://github.com/langium/langium). I found there was an open issue with it too:
https://github.com/langium/langium/issues/999

I think we will consider to support it when this issue is resolved by langium.

**Comment by ymc9** [comment]
Closing for now since there's no immediate plan.

**Comment by ymc9** [comment]
Related discussion here:

https://github.com/zenstackhq/zenstack/discussions/414
