### ISSUE TITLE
[Feature Request] Field-level policy: provide a way to "override" model-level rules

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#809]
Today, for having access to a field, both model-level and field-level (if any) policies need to be satisfied. This can be very inconvenient for scenarios where a user can only update one field but nothing else.

Concrete example:
- Admin users can update all fields of "User" model
- Regular users can only update "password" field of their own

To allow the second rule, we have to let regular users pass model-level "update" policies, however, then we have to add "@deny" rule on all fields except for "password".

The proposed solution, as discussed with @jasonmacdonald , is to introduce a third parameter to "@allow" attribute to let it "override" model-level policies:

```prisma
password String @allow('update', auth() == this, true)
```

Discord thread: https://discord.com/channels/1035538056146595961/1171196847797325854

**Comment by ymc9** [comment]
Hi @jasonmacdonald , you also mentioned another case:

> Another use-case is the profile relation. If you want to update your Profile, you must update it through a  direct profile query if not admin, because any query which  "passes through"  the user model as nested updates are immediately revoked by the User policy, even if the only field you are trying to update is allowed at the field level.

Could you show the Prisma query that you want to make work? I just want to make sure it's also covered in the implementation. Thanks!

**Comment by jasonmacdonald** [comment]
> Hi @jasonmacdonald , you also mentioned another case:
> 
> > Another use-case is the profile relation. If you want to update your Profile, you must update it through a  direct profile query if not admin, because any query which  "passes through"  the user model as nested updates are immediately revoked by the User policy, even if the only field you are trying to update is allowed at the field level.
> 
> Could you show the Prisma query that you want to make work? I just want to make sure it's also covered in the implementation. Thanks!

Really, it's the same as the first, only on a relation rather than a property. 

Example:
```
password String @allow('update', auth() == this, true)
profileId    String   @unique 
profile      Profile  @relation(fields: [profileId], references: [id], onDelete: Cascade) @allow('update', auth() == this, true)
```

This way, it's still possible to update the Profile model while performing a User update.
```
{
   data: {
      password: '12345'
      profile: {
         update: {
            phonenumber: '555-555-5555'
         }
      }
   }
}
```
I would assume the ability to resolve the first scenario though would likely just work for the second, so it might just be a matter of ensuring it works.

**Comment by ymc9** [comment]
Got it. Thanks for providing the details.

I'm actually thinking, if only "profile" is updated, it probably shouldn't trigger `User`'s "update" check at all (both model-level and field-level), since it's not really touching User. I need to think a bit more about this ...

**Comment by jasonmacdonald** [comment]
> Got it. Thanks for providing the details.
> 
> I'm actually thinking, if only "profile" is updated, it probably shouldn't trigger `User`'s "update" check at all (both model-level and field-level), since it's not really touching User. I need to think a bit more about this ...

Yes, when no `User` fields are changed, just skipping the `User` model checks makes sense, provided the `Profile` policies are still run against its nested changes - I assume that would be the case.

**Comment by tlancina** [comment]
Just to chime in because I've run into this as well - is there a reason why instead of a third parameter to field level policies, they couldn't always be checked instead of eagerly denying?

```prisma
model User {
  @@allow('update', auth().role == 'ADMIN')
  
  name     String
  email    String
  password String @allow('update', auth() == this)
}
```

This was intuitively how I assumed it worked at first, going from less specific -> more specific.

> I'm actually thinking, if only "profile" is updated, it probably shouldn't trigger `User`'s "update" check at all (both model-level and field-level), since it's not really touching User. I need to think a bit more about this ...

Could there potentially be scenarios with indirect leakage of something a User "owns"? Meaning the relation itself should still be subject to a policy.

Contrived example: `Comments` can also be created anonymously and a request comes in to update all of your `Comments`, but since `auth()` is not checked at the `Comment` model level, the update succeeds. Hard to imagine the application code that would lead to this, but semantically hopefully you see the point 😂
