### ISSUE TITLE
CLI generates error message in vercel environment

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#931]
![image](https://github.com/zenstackhq/zenstack/assets/104139426/d6a71e2a-54f3-44da-a1a9-f5924ac0510b)

**Comment by Azzerty23** [comment]
I have the impression that the issue comes from the `node-machine-id` package, and more specifically, from the `machineIdSync()` function, which doesn't work on all environments (non-shell). In Zenstack, it is used in the [Telemetry class](https://github.com/zenstackhq/zenstack/blob/main/packages/schema/src/telemetry.ts#L35C31-L35C44). There is this problem with Strapi on AWS Amplify: [https://github.com/strapi/strapi/issues/8893](https://github.com/strapi/strapi/issues/8893). To work around this, they replaced `machineIdSync()` with `uuid()` in a try-catch block: [https://github.com/strapi/strapi/pull/12173/files](https://github.com/strapi/strapi/pull/12173/files).

**Comment by Azzerty23** [comment]
I believe this will resolve the warning. Please guide me, or feel free to disregard the PR if the implementation doesn't align with your expectations.

**Comment by ymc9** [comment]
> I believe this will resolve the warning. Please guide me, or feel free to disregard the PR if the implementation doesn't align with your expectations.

Ah, that makes sense! I had suspicions about telemetry too. Thanks for making the PR! I'll follow up over there.
