### ISSUE TITLE
[Feature Request] Add support for JetBrains 2022 or older to your ZenStack Language Tools

### ISSUE THREAD

**Issue by vbg8exadel** [zenstackhq/zenstack#973]
I am using IntelliJ IDEA 2022.3.3 due to license limitation and can't upgrade to the newer one.
![image](https://github.com/zenstackhq/zenstack/assets/145759001/80ad1643-68be-4170-aa21-23f863b583b1)

I tried to install the [ZenStack Language Tools](https://plugins.jetbrains.com/plugin/23397-zenstack-language-tools) but got error:
![2024-01-30 12_59_47-ZenStack Language Tools - IntelliJ IDEs Plugin _ Marketplace](https://github.com/zenstackhq/zenstack/assets/145759001/a032e563-451f-4b9c-8db5-fec489af20d9)

There is a compatibility block on your ZenStack Language Tools for Jetbrains. It won't install on 2022.x.x versions.

**Describe the solution you'd like**
Please add support for Jetbrains 2022 or older ones as there many developers who is using "Perpetual fallback license" for their Jetbrains tools. See more about it here: 

1. [What is a perpetual fallback license?](https://sales.jetbrains.com/hc/en-gb/articles/207240845)
2. [How do I activate and use my perpetual fallback license?](https://sales.jetbrains.com/hc/en-gb/articles/360001186840-How-do-I-activate-and-use-my-perpetual-fallback-license)

**Comment by ymc9** [comment]
Hi @vbg8exadel , thanks for reporting this. We'd love to support older versions of JetBrains, However ZenStack's extension is implemented with the LSP support, which is only available since 2023.2.

https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

The LSP support allows us to use one implementation to support both VSCode and JetBrains. We don't have a plan to reimplement an extension using JetBrain's proprietary language extensions API yet.
