### ISSUE TITLE
[Feature Request] Add SvelteKit support in tRPC plugin

### ISSUE THREAD

**Issue by brunobely** [zenstackhq/zenstack#985]
**Is your feature request related to a problem? Please describe.**
The tRPC plugin supports the `generateClientHelpers` option, but only `react` and `next` are supported as values.

**Describe the solution you'd like**
It would be nice to have SvelteKit helpers generated as well.

**Describe alternatives you've considered**
I am currently using [trpc-sveltekit](https://github.com/icflorescu/trpc-sveltekit) to create the tRPC client.

**Comment by ymc9** [comment]
Hi @brunobely , thanks for bringing this up. SvelteKit helper wasn't supported because I didn't find an official package from trpc side. trpc-sveltekit seems to be the defacto integration for now. Adding support to it shouldn't be too hard. I hope we can add it in the next release.

Also, please let me know if you're interested in making a PR. I'll be happy to facilitate.

**Comment by brunobely** [comment]
Absolutely, I'd love to help.
